[project]
name = "weather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.2.2",
    "httpx>=0.28.1",
    "langchain>=0.3.24",
    "mcp[cli]>=1.6.0",
    "openai>=1.76.0",
    "streamlit>=1.44.1",
]
